"""Shared feature configuration for training and inference."""

FEATURE_COLS = [
    "RSI",
    "SMA_50",
    "SMA_20",
    "EMA_20",
    "Rolling_Volatility_30",
    "Rolling_Volatility_10",
    "Daily_Return",
    "ROC_10",
    "MACD",
    "MACD_Signal",
    "MACD_Hist",
    "BB_Width",
    "NAV_to_SMA50_Ratio",
    "Volatility_Ratio",
    "Return_5",
    "Return_20",
    "Sharpe_30",
    "ZScore_20",
    "Drawdown_60",
]

FEATURE_KEY_MAP = {
    "rsi": "RSI",
    "sma_50": "SMA_50",
    "sma_20": "SMA_20",
    "ema_20": "EMA_20",
    "rolling_volatility_30": "Rolling_Volatility_30",
    "rolling_volatility_10": "Rolling_Volatility_10",
    "daily_return": "Daily_Return",
    "roc_10": "ROC_10",
    "macd": "MACD",
    "macd_signal": "MACD_Signal",
    "macd_hist": "MACD_Hist",
    "bb_width": "BB_Width",
    "nav_to_sma50_ratio": "NAV_to_SMA50_Ratio",
    "volatility_ratio": "Volatility_Ratio",
    "return_5": "Return_5",
    "return_20": "Return_20",
    "sharpe_30": "Sharpe_30",
    "zscore_20": "ZScore_20",
    "drawdown_60": "Drawdown_60",
}
